### ISSUE TITLE
Maker/Taker

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#2]
it never use maker/taker
allways try to buy for low price

// % to mark up or down price for orders
c.markup_pct = 2
its allways price - 2%

**Comment by crack00r** [comment]
as i sayd here
https://github.com/carlos8f/zenbot/issues/500

on cryptopings pings you want a 100% buy to get onto the train, so you need to set a price ABOVE the marked, not UNDER the current bid

**Comment by crack00r** [comment]
i see, you had the same problem here
https://github.com/carlos8f/zenbot/issues/360

how to fix this?

**Comment by TheRoboKitten** [comment]
Not sure to be honest, what really needs to happen is the buy and sell percents markup and down split into two input variables. Such as markdown percent. (this doesnt exist.) I'll keep this open until they fix it :)

**Comment by TheRoboKitten** [comment]
I also noticed, that the engine.js and exchange.js dont appear to use taker mode on poloniex at all. Not sure, but my taker fee is always .15% on polo... Its quite a mystery since the exchange.js needs an overhaul by the plugin creator over at the zenbot github. (If I recall, taker was never supported haha)

**Comment by crack00r** [comment]
fixed: https://github.com/TheRoboKitten/ZenAii/pull/5
