### ISSUE TITLE
MessageIdInvalidError

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#4]
(MessageIdInvalidError(...), 'The specified message ID is invalid.')

**Comment by TheRoboKitten** [comment]
This is very common with the forward, usually just type into the telegram bot's window, and if it returns a smaller sized digit in the shell window it should forward messages to you, but in general, the message forwarding isnt completely required for functionality. This is a bug, that I likely won't fix due to the telegram api data that is received or I will remove the forwarding code. (For example.... sometimes telegram sends a message that has "supergroup" message IDs... Instead of a person-to-person ID... I am not sure why and I think this could be because of the bot api on telegrams end. So In short, I set the system to buy when it sees any coin such as #XMR appear in the message data.

Though if there is another issue with buying/selling with the signals not being read I'll gladly help fix that :)

**Comment by TheRoboKitten** [comment]
Since it was originally made to work with cryptoping, and cryptoalert does not support this style of message forwarding for security I'm going to close this! Sorry Crack00r.... ;)
